# Generated by Django 4.2.2 on 2023-06-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinazione',
            fields=[
                ('destinazione_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('paese', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dettagli_passeggero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('eta', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('indirizzo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('indirizzo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destinazione')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('prenotazione_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('numero_persone', models.PositiveIntegerField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('prezzo', models.PositiveIntegerField()),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destinazione')),
            ],
        ),
    ]
