# Generated by Django 4.2.2 on 2023-06-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='metodo_pagamento',
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('giorni', models.PositiveIntegerField()),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destinazione')),
            ],
        ),
    ]
