# Generated by Django 4.2.2 on 2023-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_itinerario_giorni_itinerario_day1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='day1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='day7',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
