# Generated by Django 4.2.2 on 2023-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_itinerario_day1_alter_itinerario_day2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
