# Generated by Django 4.2.2 on 2023-06-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_itinerario_prezzo_prenotazione_nome_completo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dettagli_passeggero',
        ),
    ]
